#!/bin/bash -e
# GitHubToBlih Copyright (C) 2020 Maxime Houis
# This program comes with ABSOLUTELY NO WARRANTY.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see LICENSE for details.

if [[ $# != 1 ]]; then
    echo "Usage: $0 REPO_NAME"
    exit 1
fi

TMP_DIR="./tmp_blih"

# Define it in your environment or fill in your usernames
USER_GHUB="$USER_GHUB"
USER_BLIH="$USER_BLIH"

REPO_GHUB="$1"
REPO_BLIH="$1"

set -xe

rm -rf $TMP_DIR
mkdir $TMP_DIR

git clone --bare git@github.com:$USER_GHUB/$REPO_GHUB $TMP_DIR
cd $TMP_DIR
git push --mirror git@git.epitech.eu:$USER_BLIH/$REPO_BLIH

cd $OLDPWD
rm -rf $TMP_DIR
